# Generated by Django 3.2 on 2021-04-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pawpawserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.DateTimeField(auto_now_add=True)),
                ('Model', models.BooleanField(default=False)),
                ('Instrument', models.TextField(blank=True, default='', max_length=100)),
                ('Timestamp', models.TextField()),
                ('Value', models.TextField()),
            ],
            options={
                'ordering': ['Timestamp'],
            },
        ),
    ]
