# Generated by Django 3.2 on 2021-04-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpawserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pawpawserver',
            new_name='TimeSeriesDatum',
        ),
    ]
